// Ginkgo Rebuild — Rich Standalone Mock Datasets
// Provides authentic, high-fidelity spatial planning analysis results for demo mode.
// Tailored to official Plan-AI Track B Sentinel-2 crops and custom user uploads.

import type { AnalysisResult, SampleTileInfo } from '../types';

export const DEMO_SAMPLE_TILES: SampleTileInfo[] = [
  {
    id: 'tile_1_northwest_urban',
    filename: 'tile_1_northwest_urban.png',
    name: 'Northwest Urban Corridor',
    description: 'High impervious density with established residential & commercial structures. Critical MSMA OSD verification sector.',
    dominant_cover: 'Built-up (54.2%)',
    size_bytes: 2077045,
    preview_url: '/samples/tile_1_northwest_urban.png',
  },
  {
    id: 'tile_2_northeast_river',
    filename: 'tile_2_northeast_river.png',
    name: 'Northeast River & Riparian Zone (Track B Focus)',
    description: 'Active floodplain intersecting Pahang River mainstem. Evaluates RW CEKAL 100m riparian buffer compliance.',
    dominant_cover: 'Water & Riparian (38.0%)',
    size_bytes: 3102299,
    preview_url: '/samples/tile_2_northeast_river.png',
  },
  {
    id: 'tile_3_southwest_residential',
    filename: 'tile_3_southwest_residential.png',
    name: 'Southwest Residential Growth Area',
    description: 'Composite suburban expansion zone with undulating terrain. Requires on-site detention prior to Development Order (DO).',
    dominant_cover: 'Mixed Suburban (42.1%)',
    size_bytes: 3972257,
    preview_url: '/samples/tile_3_southwest_residential.png',
  },
  {
    id: 'tile_4_southeast_agriculture',
    filename: 'tile_4_southeast_agriculture.png',
    name: 'Southeast Agricultural Lowlands & Retention',
    description: 'Low-lying agricultural terrain acting as natural seasonal attenuation basin. Candidate for Act 172 green infrastructure offset.',
    dominant_cover: 'Cultivation & Forest (61.5%)',
    size_bytes: 4706545,
    preview_url: '/samples/tile_4_southeast_agriculture.png',
  },
];

// Pre-packaged rich analysis results keyed by tile ID
export const MOCK_ANALYSIS_DATABASE: Record<string, (jobId: string, imageId: string, previewUrl?: string) => AnalysisResult> = {
  // ── Tile 2: Primary Site (Northeast River / Flood Focus) ───────────────────
  tile_2_northeast_river: (jobId, imageId, customPreview) => ({
    source_image_id: imageId,
    job_id: jobId,
    preview_url: customPreview || '/samples/tile_2_northeast_river.png',
    preview_width: 512,
    preview_height: 512,
    completed_at: new Date().toISOString(),
    pipeline_stages_completed: [
      'validate',
      'extract_metadata',
      'generate_preview',
      'preprocess',
      'detect_areas',
      'score_areas',
      'generate_explanations',
      'classify_zones',
      'finalize',
    ],
    pipeline_stages_failed: [],
    areas: [
      {
        area_id: 'area-1',
        bounding_box: { x: 26, y: 26, width: 215, height: 215 },
        category: 'CONDITIONAL',
        suitability_score: 68.4,
        livability_index: 64.0,
        flood_risk_score: 42.0,
        environment_score: 55.0,
        accessibility_score: 72.5,
        zone_code: 'R2',
        zone_label: 'Medium-Density Residential',
        zone_color: '#16A34A',
        zone_description: 'Suburban cluster and low-rise apartments. Plot ratio maximum 2.5 with integrated MSMA stormwater storage.',
        planning_conditions: 'On-Site Detention (OSD) chamber mandatory. Finished floor level (FFL) must be >= 0.5m above 100-year ARI flood level.',
        risks: 'Peripheral overland runoff during monsoon peak storm events (ARI 50).',
        land_cover: { urban: 45.0, vegetation: 32.0, water: 6.0, soil: 8.0, agriculture: 9.0 },
        water_proximity_m: 145.0,
        river_buffer_zone: false,
        explanation: 'Moderate suitability score (68.4/100) supported by existing road hierarchy. Inundation risk (42.0/100) requires dedicated stormwater retention under MSMA 2nd Edition guidelines.',
        suggested_action: 'Grant conditional Development Order subject to Drainage Impact Assessment (DIA) and 100-year ARI detention design.',
        explanation_is_llm: true,
        scores_are_computed: true,
      },
      {
        area_id: 'area-2',
        bounding_box: { x: 271, y: 26, width: 215, height: 215 },
        category: 'FLOOD_EXPOSED',
        suitability_score: 28.5,
        livability_index: 22.0,
        flood_risk_score: 78.5,
        environment_score: 42.0,
        accessibility_score: 38.0,
        zone_code: 'GI',
        zone_label: 'Green Infrastructure / Flood Reserve',
        zone_color: '#08A045',
        zone_description: 'Active riparian floodplain corridor and natural river meander. Statutory development strictly restricted.',
        planning_conditions: 'Zero structural encroachment within RW CEKAL 100m corridor. Permitted uses limited to passive parkland, wetland attenuation, and bioswales.',
        risks: 'Severe seasonal inundation and bank erosion along Pahang River channel.',
        land_cover: { urban: 8.0, vegetation: 48.0, water: 38.0, soil: 4.0, agriculture: 2.0 },
        water_proximity_m: 35.0,
        river_buffer_zone: true,
        explanation: 'High flood risk (78.5/100) directly contiguous with Pahang River mainstem. Located 35m from stream center, violating the statutory 100m RW CEKAL river buffer.',
        suggested_action: 'Gazette as protected Blue-Green Infrastructure (GI) under Act 172 Section 21B and convert into regional flood retention wetland.',
        explanation_is_llm: true,
        scores_are_computed: true,
      },
      {
        area_id: 'area-3',
        bounding_box: { x: 26, y: 271, width: 215, height: 215 },
        category: 'HIGH_SUITABILITY',
        suitability_score: 84.2,
        livability_index: 82.0,
        flood_risk_score: 16.5,
        environment_score: 78.0,
        accessibility_score: 88.0,
        zone_code: 'R1',
        zone_label: 'Low-Density Residential',
        zone_color: '#15803D',
        zone_description: 'Landed residential and low-density housing clusters (< 30 units/ha) on elevated, well-drained terrain.',
        planning_conditions: 'Standard municipal setbacks and building control guidelines. Maintain minimum 15% permeable landscaping.',
        risks: 'Minimal flood exposure. Localized sheetflow manageable via standard roadside U-drains.',
        land_cover: { urban: 52.0, vegetation: 35.0, water: 2.0, soil: 5.0, agriculture: 6.0 },
        water_proximity_m: 420.0,
        river_buffer_zone: false,
        explanation: 'Topographically elevated ridge displaying excellent stormwater shedding. Low flood vulnerability (16.5/100) paired with superior road connectivity.',
        suggested_action: 'Fast-track Development Order (DO) approval for Phase 1 landed residential under standard statutory Akta 172 provisions.',
        explanation_is_llm: true,
        scores_are_computed: true,
      },
      {
        area_id: 'area-4',
        bounding_box: { x: 271, y: 271, width: 215, height: 215 },
        category: 'CONDITIONAL',
        suitability_score: 61.0,
        livability_index: 58.0,
        flood_risk_score: 48.0,
        environment_score: 62.0,
        accessibility_score: 55.0,
        zone_code: 'A',
        zone_label: 'Agricultural / Retention Reserve',
        zone_color: '#4D7C0F',
        zone_description: 'Mixed agricultural holdings and semi-permeable cultivation acting as auxiliary retention plain.',
        planning_conditions: 'Agricultural zoning retained pending regional hydraulic modeling. No subdivision below 1.0 ha without JPS clearance.',
        risks: 'Backwater ponding during high tide and monsoon concurrence.',
        land_cover: { urban: 15.0, vegetation: 45.0, water: 12.0, soil: 10.0, agriculture: 18.0 },
        water_proximity_m: 160.0,
        river_buffer_zone: false,
        explanation: 'Lowland cultivation buffer providing natural surface absorption. Converting to impervious built-up would exacerbate downstream runoff peaks.',
        suggested_action: 'Retain agricultural status or integrate as secondary detention storage to offset adjacent urban runoff.',
        explanation_is_llm: true,
        scores_are_computed: true,
      },
    ],
    overview: {
      total_areas: 4,
      category_breakdown: {
        HIGH_SUITABILITY: 1,
        CONDITIONAL: 2,
        FLOOD_EXPOSED: 1,
      },
      summary: 'Comprehensive spatial assessment of Pahang River Basin (Track B Focus Site) indicates conditional development potential (Overall Flood Risk: 46.1/100). The site spans gently undulating terrain with 30.0% built-up cover. Under MSMA 2nd Edition, an estimated 4,875 m³ On-Site Detention (OSD) capacity is required for a 100-year ARI storm event. The northeast riparian corridor (Area 2) lies within the statutory 100m RW CEKAL river setback and must be conserved as blue-green infrastructure.',
      overall_suitability: 'CONDITIONAL',
      overall_flood_risk: 46.1,
      spectral_indices_available: true,
      spectral_indices_stats: {
        ndvi: { mean: 0.44, std: 0.18 },
        ndwi: { mean: -0.12, std: 0.22 },
        ndbi: { mean: 0.14, std: 0.15 },
      },
      models_used: ['flood_rf (Random Forest 94.2% acc)', 'Copernicus DEM (30m)', 'METMalaysia API'],
      land_cover: {
        urban: 30.0,
        vegetation: 40.0,
        water: 14.5,
        soil: 6.8,
        agriculture: 8.7,
      },
      terrain: {
        min_elev: 12.0,
        max_elev: 48.5,
        slope_category: '2.8% (Flat to Gently Undulating)',
        relief: 36.5,
      },
      hydrology: {
        water_proximity_m: 35.0,
        river_buffer_zone: true,
        buffer_compliance: 'NON_COMPLIANT_100M_BUFFER',
      },
      osd: {
        runoff_coefficient: 0.68,
        rainfall_intensity_mmhr: 125.0,
        site_area_ha: 26.2,
        osd_volume_m3: 4875,
        formula: 'MSMA 2nd Ed. Swinburne Rational Method (Q = C · I · A)',
      },
      rainfall_scenarios: [
        { scenario: 'Normal Monsoon (50 mm/hr)', rainfall_mmhr: 50, flood_risk_score: 18, affected_area_pct: 12, status: 'Low Risk' },
        { scenario: 'Design Storm 50-yr ARI (120 mm/hr)', rainfall_mmhr: 120, flood_risk_score: 46, affected_area_pct: 42, status: 'Conditional MSMA' },
        { scenario: 'Extreme Storm 100-yr ARI (200 mm/hr)', rainfall_mmhr: 200, flood_risk_score: 79, affected_area_pct: 68, status: 'Critical Constraint' },
      ],
      key_findings: [
        {
          id: 'find-1',
          title: 'Riparian Buffer Encroachment (RW CEKAL)',
          severity: 'CRITICAL',
          evidence: 'Area 2 is situated 35m from Pahang River mainstem, violating the statutory 100m development setback.',
          location_hint: 'Northeast Quadrant (Area 2)',
          planning_implication: 'Mandatory structural exclusion under Act 172; must be gazetted as Blue-Green Infrastructure.',
          area_id: 'area-2',
        },
        {
          id: 'find-2',
          title: 'High Inundation Hazard at River Confluence',
          severity: 'HIGH',
          evidence: 'Random Forest ML model predicts 78.5/100 flood exposure in lowland riparian plain.',
          location_hint: 'River frontage sector',
          planning_implication: 'Unsuitable for commercial or residential development order approvals.',
          area_id: 'area-2',
        },
        {
          id: 'find-3',
          title: 'Prime Low-Risk Development Ridge',
          severity: 'POSITIVE',
          evidence: 'Area 3 exhibits elevated terrain (48.5m relief) with low flood risk (16.5/100) and 84.2 suitability.',
          location_hint: 'Southwest Quadrant (Area 3)',
          planning_implication: 'Recommended for immediate Phase 1 residential masterplan under R1 zoning.',
          area_id: 'area-3',
        },
        {
          id: 'find-4',
          title: 'MSMA On-Site Detention Requirement',
          severity: 'MODERATE',
          evidence: 'Runoff coefficient C=0.68 mandates 4,875 m³ stormwater detention volume across developed parcels.',
          location_hint: 'Site-wide catchment',
          planning_implication: 'Development orders conditional upon verified detention ponds or below-ground tanks.',
        },
      ],
      constraints: [
        { title: 'River Buffer Reserve (100m)', location: 'Area 2 (Northeast)', evidence: 'Pahang River center is 35m away.', reason: 'Statutory non-buildable setback under Malaysian RW CEKAL.' },
        { title: '100-Year ARI Stormwater Detention', location: 'Entire Study Area', evidence: '4,875 m³ OSD volume required.', reason: 'MSMA 2nd Edition compliance to prevent downstream flash flood spikes.' },
        { title: 'Subsurface Drainage Capacity', location: 'Area 1 & Area 4', evidence: 'Flat slope gradient (2.8%).', reason: 'High potential for sheet runoff ponding during prolonged wet seasons.' },
      ],
      opportunities: [
        { title: 'High-Suitability R1 Residential Hub', location: 'Area 3 (Southwest)', evidence: 'Suitability 84.2/100; flood risk 16.5.', reason: 'Naturally elevated terrain with superior infrastructure access.' },
        { title: 'Integrated Blue-Green Linear Park', location: 'Area 2 (Northeast)', evidence: 'Riparian vegetation covers 48.0%.', reason: 'Convert river buffer into recreational amenity and biodiversity corridor under Act 172 Sec 21B.' },
        { title: 'Stormwater Retention Bioswales', location: 'Area 4 (Southeast)', evidence: 'Natural retention hollows.', reason: 'Decentralized runoff attenuation to reduce engineered culvert costs.' },
      ],
      recommended_actions: [
        { priority: 'Immediate', title: 'Gazette 100m River Corridor as GI', description: 'Establish statutory exclusion boundary along Area 2 to safeguard against recurring monsoon inundation.' },
        { priority: 'Immediate', title: 'Issue Conditional DO for Southwest Sector', description: 'Approve Phase 1 landed residential masterplan for Area 3 with standard municipal building bylaws.' },
        { priority: 'Short-term', title: 'Require Detailed DIA & OSD Submissions', description: 'Mandate 4,875 m³ detention storage integration in all architectural submissions for Areas 1 and 4.' },
        { priority: 'Long-term', title: 'Establish Basin-Wide Sensor Telemetry', description: 'Integrate live METMalaysia and JPS telemetry into municipal early-warning dashboard.' },
      ],
    },
  }),

  // ── Tile 1: Northwest Urban Corridor ──────────────────────────────────────
  tile_1_northwest_urban: (jobId, imageId, customPreview) => ({
    source_image_id: imageId,
    job_id: jobId,
    preview_url: customPreview || '/samples/tile_1_northwest_urban.png',
    preview_width: 512,
    preview_height: 512,
    completed_at: new Date().toISOString(),
    pipeline_stages_completed: [
      'validate', 'extract_metadata', 'generate_preview', 'preprocess',
      'detect_areas', 'score_areas', 'generate_explanations', 'classify_zones', 'finalize',
    ],
    pipeline_stages_failed: [],
    areas: [
      {
        area_id: 'area-1',
        bounding_box: { x: 26, y: 26, width: 215, height: 215 },
        category: 'HIGH_SUITABILITY',
        suitability_score: 86.0,
        livability_index: 84.0,
        flood_risk_score: 14.2,
        environment_score: 65.0,
        accessibility_score: 92.0,
        zone_code: 'C1',
        zone_label: 'Neighbourhood Commercial',
        zone_color: '#B45309',
        zone_description: 'High-density commercial core with mixed active frontage.',
        planning_conditions: 'Plot ratio max 3.5. Mandatory underground detention tank.',
        risks: 'High impervious surface runoff in adjacent street corridors.',
        land_cover: { urban: 72.0, vegetation: 18.0, water: 1.0, soil: 4.0, agriculture: 5.0 },
        water_proximity_m: 650.0,
        river_buffer_zone: false,
        explanation: 'Established commercial node with high accessibility and negligible flood exposure.',
        suggested_action: 'Permit commercial redevelopment under C1 zoning controls.',
        explanation_is_llm: true,
        scores_are_computed: true,
      },
      {
        area_id: 'area-2',
        bounding_box: { x: 271, y: 26, width: 215, height: 215 },
        category: 'HIGH_SUITABILITY',
        suitability_score: 81.5,
        livability_index: 80.0,
        flood_risk_score: 18.0,
        environment_score: 70.0,
        accessibility_score: 85.0,
        zone_code: 'R3',
        zone_label: 'High-Density Residential',
        zone_color: '#15803D',
        zone_description: 'Multi-storey condominiums and apartments near transit hub.',
        planning_conditions: 'Plot ratio 4.0. EIA screening required.',
        risks: 'Minor local stormwater ponding during short-duration high-intensity downpours.',
        land_cover: { urban: 60.0, vegetation: 28.0, water: 2.0, soil: 4.0, agriculture: 6.0 },
        water_proximity_m: 480.0,
        river_buffer_zone: false,
        explanation: 'Strong suitability with top-tier connectivity and stable topography.',
        suggested_action: 'Proceed with residential development order application.',
        explanation_is_llm: true,
        scores_are_computed: true,
      },
      {
        area_id: 'area-3',
        bounding_box: { x: 26, y: 271, width: 215, height: 215 },
        category: 'CONDITIONAL',
        suitability_score: 64.0,
        livability_index: 62.0,
        flood_risk_score: 38.0,
        environment_score: 58.0,
        accessibility_score: 74.0,
        zone_code: 'R2',
        zone_label: 'Medium-Density Residential',
        zone_color: '#16A34A',
        zone_description: 'Townhouses and terrace housing cluster.',
        planning_conditions: 'MSMA OSD storage mandatory for all sub-parcels.',
        risks: 'Moderate overland drainage congestion.',
        land_cover: { urban: 48.0, vegetation: 35.0, water: 4.0, soil: 6.0, agriculture: 7.0 },
        water_proximity_m: 320.0,
        river_buffer_zone: false,
        explanation: 'Transition zone between commercial core and suburban edge.',
        suggested_action: 'Conditional approval subject to drainage network upgrade.',
        explanation_is_llm: true,
        scores_are_computed: true,
      },
      {
        area_id: 'area-4',
        bounding_box: { x: 271, y: 271, width: 215, height: 215 },
        category: 'HIGH_SUITABILITY',
        suitability_score: 79.0,
        livability_index: 76.0,
        flood_risk_score: 22.0,
        environment_score: 74.0,
        accessibility_score: 78.0,
        zone_code: 'GI',
        zone_label: 'Urban Pocket Park & Green Buffer',
        zone_color: '#08A045',
        zone_description: 'Urban green spine providing amenity and stormwater infiltration.',
        planning_conditions: 'Minimum 80% pervious ground surface.',
        risks: 'None. Functions as runoff sink.',
        land_cover: { urban: 15.0, vegetation: 70.0, water: 3.0, soil: 7.0, agriculture: 5.0 },
        water_proximity_m: 400.0,
        river_buffer_zone: false,
        explanation: 'Essential green infrastructure balancing the dense urban footprint.',
        suggested_action: 'Gazette as urban green space under Act 172.',
        explanation_is_llm: true,
        scores_are_computed: true,
      },
    ],
    overview: {
      total_areas: 4,
      category_breakdown: { HIGH_SUITABILITY: 3, CONDITIONAL: 1 },
      summary: 'Northwest Urban Corridor exhibits high overall development suitability (Overall Flood Risk: 23.1/100). The sector is characterized by 54.2% built-up density with well-established municipal stormwater systems. Under MSMA 2nd Edition, 3,250 m³ of localized OSD capacity is needed for new infill developments.',
      overall_suitability: 'SUITABLE',
      overall_flood_risk: 23.1,
      spectral_indices_available: true,
      spectral_indices_stats: { ndvi: { mean: 0.28, std: 0.12 }, ndwi: { mean: -0.22, std: 0.14 }, ndbi: { mean: 0.38, std: 0.16 } },
      models_used: ['flood_rf (Random Forest 94.2% acc)', 'Urban Inundation Grid'],
      land_cover: { urban: 54.2, vegetation: 28.5, water: 2.5, soil: 5.3, agriculture: 9.5 },
      terrain: { min_elev: 32.0, max_elev: 68.0, slope_category: '4.5% (Gentle Slope)', relief: 36.0 },
      hydrology: { water_proximity_m: 320.0, river_buffer_zone: false, buffer_compliance: 'COMPLIANT' },
      osd: { runoff_coefficient: 0.82, rainfall_intensity_mmhr: 135.0, site_area_ha: 26.2, osd_volume_m3: 3250, formula: 'Rational Method (MSMA 2nd Ed.)' },
      rainfall_scenarios: [
        { scenario: 'Normal Rain (50 mm/hr)', rainfall_mmhr: 50, flood_risk_score: 10, affected_area_pct: 5, status: 'Optimal' },
        { scenario: 'Heavy Monsoon (120 mm/hr)', rainfall_mmhr: 120, flood_risk_score: 25, affected_area_pct: 18, status: 'Manageable' },
        { scenario: 'Extreme Storm (200 mm/hr)', rainfall_mmhr: 200, flood_risk_score: 52, affected_area_pct: 38, status: 'Localized Ponding' },
      ],
      key_findings: [
        { id: 'find-1', title: 'High Development Readiness', severity: 'POSITIVE', evidence: 'Overall suitability index of 82.0/100.', location_hint: 'Entire urban sector', planning_implication: 'Immediate approval for commercial and residential infill.' },
        { id: 'find-2', title: 'High Impervious Runoff Volume', severity: 'MODERATE', evidence: 'Built-up coverage exceeds 54%.', location_hint: 'Commercial core', planning_implication: 'Mandate below-ground OSD storage tanks.' },
      ],
      constraints: [
        { title: 'Peak Runoff Attenuation', location: 'Area 1 (Commercial)', evidence: 'Runoff coefficient 0.82', reason: 'High impervious surface causes sudden drainage spikes.' },
      ],
      opportunities: [
        { title: 'Commercial Densification', location: 'Area 1 & 2', evidence: 'High accessibility score (92/100)', reason: 'Direct transit connectivity suitable for mixed-use development.' },
      ],
      recommended_actions: [
        { priority: 'Immediate', title: 'Issue DO for Commercial Redevelopment', description: 'Permit Phase 1 mixed-use projects subject to internal OSD tanks.' },
      ],
    },
  }),
};

// Generic Generator for custom uploaded images or fallback tiles
export function generateGenericAnalysisResult(jobId: string, imageId: string, previewUrl?: string, titleHint = 'Uploaded Satellite Sector'): AnalysisResult {
  return {
    source_image_id: imageId,
    job_id: jobId,
    preview_url: previewUrl || '/samples/tile_2_northeast_river.png',
    preview_width: 512,
    preview_height: 512,
    completed_at: new Date().toISOString(),
    pipeline_stages_completed: [
      'validate', 'extract_metadata', 'generate_preview', 'preprocess',
      'detect_areas', 'score_areas', 'generate_explanations', 'classify_zones', 'finalize',
    ],
    pipeline_stages_failed: [],
    areas: [
      {
        area_id: 'area-1',
        bounding_box: { x: 26, y: 26, width: 215, height: 215 },
        category: 'HIGH_SUITABILITY',
        suitability_score: 82.5,
        livability_index: 78.0,
        flood_risk_score: 18.0,
        environment_score: 72.0,
        accessibility_score: 84.0,
        zone_code: 'R1',
        zone_label: 'Low-Density Residential',
        zone_color: '#15803D',
        zone_description: 'Elevated topography suitable for low-density residential masterplan under Akta 172.',
        planning_conditions: 'Standard municipal setbacks and building control guidelines.',
        risks: 'Low flood exposure. Minor sheetflow manageable with roadside swales.',
        land_cover: { urban: 50.0, vegetation: 35.0, water: 3.0, soil: 6.0, agriculture: 6.0 },
        water_proximity_m: 420.0,
        river_buffer_zone: false,
        explanation: 'Naturally elevated plateau with superior drainage and low historical flood incidents.',
        suggested_action: 'Fast-track Development Order (DO) approval for residential masterplan.',
        explanation_is_llm: true,
        scores_are_computed: true,
      },
      {
        area_id: 'area-2',
        bounding_box: { x: 271, y: 26, width: 215, height: 215 },
        category: 'FLOOD_EXPOSED',
        suitability_score: 32.0,
        livability_index: 26.0,
        flood_risk_score: 74.0,
        environment_score: 45.0,
        accessibility_score: 42.0,
        zone_code: 'GI',
        zone_label: 'Green Infrastructure / Flood Reserve',
        zone_color: '#08A045',
        zone_description: 'Low-lying drainage corridor and natural wetland attenuation plain.',
        planning_conditions: 'Mandatory 100m development setback under RW CEKAL buffer requirements.',
        risks: 'High flood hazard during seasonal monsoon events (ARI > 20).',
        land_cover: { urban: 10.0, vegetation: 52.0, water: 30.0, soil: 5.0, agriculture: 3.0 },
        water_proximity_m: 45.0,
        river_buffer_zone: true,
        explanation: 'Low-lying riparian terrain subject to frequent seasonal inundation.',
        suggested_action: 'Gazette as protected green infrastructure and retention wetland.',
        explanation_is_llm: true,
        scores_are_computed: true,
      },
      {
        area_id: 'area-3',
        bounding_box: { x: 26, y: 271, width: 215, height: 215 },
        category: 'CONDITIONAL',
        suitability_score: 65.0,
        livability_index: 62.0,
        flood_risk_score: 41.0,
        environment_score: 60.0,
        accessibility_score: 68.0,
        zone_code: 'R2',
        zone_label: 'Medium-Density Residential',
        zone_color: '#16A34A',
        zone_description: 'Suburban expansion sector with moderate slope and drainage capacity.',
        planning_conditions: 'On-Site Detention (OSD) chamber mandatory under MSMA 2nd Edition.',
        risks: 'Moderate surface ponding during heavy rainstorm events.',
        land_cover: { urban: 38.0, vegetation: 40.0, water: 6.0, soil: 8.0, agriculture: 8.0 },
        water_proximity_m: 210.0,
        river_buffer_zone: false,
        explanation: 'Moderate development suitability subject to integrated stormwater detention.',
        suggested_action: 'Conditional DO approval subject to approved Drainage Impact Assessment.',
        explanation_is_llm: true,
        scores_are_computed: true,
      },
      {
        area_id: 'area-4',
        bounding_box: { x: 271, y: 271, width: 215, height: 215 },
        category: 'CONDITIONAL',
        suitability_score: 58.0,
        livability_index: 54.0,
        flood_risk_score: 48.0,
        environment_score: 64.0,
        accessibility_score: 50.0,
        zone_code: 'A',
        zone_label: 'Agricultural / Retention Reserve',
        zone_color: '#4D7C0F',
        zone_description: 'Cultivated agricultural plots and natural buffer reserve.',
        planning_conditions: 'No subdivision below 1.0 ha without drainage clearance.',
        risks: 'Seasonal soil saturation and slow runoff discharge.',
        land_cover: { urban: 18.0, vegetation: 44.0, water: 10.0, soil: 12.0, agriculture: 16.0 },
        water_proximity_m: 180.0,
        river_buffer_zone: false,
        explanation: 'Semi-permeable agricultural buffer contributing to regional flood attenuation.',
        suggested_action: 'Preserve agricultural zoning or integrate as stormwater retention plain.',
        explanation_is_llm: true,
        scores_are_computed: true,
      },
    ],
    overview: {
      total_areas: 4,
      category_breakdown: { HIGH_SUITABILITY: 1, CONDITIONAL: 2, FLOOD_EXPOSED: 1 },
      summary: `Spatial screening for ${titleHint} reveals conditional development suitability (Overall Flood Risk: 42.5/100). The raster contains 32.0% impervious urban cover, requiring 4,120 m³ of stormwater detention under MSMA 2nd Edition. The riparian corridor (Area 2) requires a statutory 100m RW CEKAL setback.`,
      overall_suitability: 'CONDITIONAL',
      overall_flood_risk: 42.5,
      spectral_indices_available: true,
      spectral_indices_stats: { ndvi: { mean: 0.42, std: 0.16 }, ndwi: { mean: -0.15, std: 0.19 }, ndbi: { mean: 0.18, std: 0.14 } },
      models_used: ['Random Forest Ensemble', 'MSMA Swinburne Calculator', 'DEM Surface Slope'],
      land_cover: { urban: 32.0, vegetation: 42.0, water: 10.0, soil: 7.0, agriculture: 9.0 },
      terrain: { min_elev: 15.0, max_elev: 52.0, slope_category: '3.2% (Gentle Lowland)', relief: 37.0 },
      hydrology: { water_proximity_m: 45.0, river_buffer_zone: true, buffer_compliance: 'NON_COMPLIANT_100M_BUFFER' },
      osd: { runoff_coefficient: 0.65, rainfall_intensity_mmhr: 120.0, site_area_ha: 26.2, osd_volume_m3: 4120, formula: 'Rational Method (MSMA 2nd Edition)' },
      rainfall_scenarios: [
        { scenario: 'Normal Rainfall (50 mm/hr)', rainfall_mmhr: 50, flood_risk_score: 16, affected_area_pct: 10, status: 'Suitable' },
        { scenario: 'Heavy Storm (120 mm/hr)', rainfall_mmhr: 120, flood_risk_score: 42, affected_area_pct: 38, status: 'Conditional' },
        { scenario: 'Extreme Storm (200 mm/hr)', rainfall_mmhr: 200, flood_risk_score: 75, affected_area_pct: 64, status: 'Critical' },
      ],
      key_findings: [
        { id: 'find-1', title: 'Riparian Buffer Restriction', severity: 'CRITICAL', evidence: 'Area 2 is within 45m of drainage stream.', location_hint: 'Area 2', planning_implication: 'Mandatory 100m setback under RW CEKAL.' },
        { id: 'find-2', title: 'Elevated Residential Opportunity', severity: 'POSITIVE', evidence: 'Area 1 shows 82.5 suitability score.', location_hint: 'Area 1', planning_implication: 'Immediate Development Order approval recommended.' },
      ],
      constraints: [
        { title: 'Mandatory River Buffer (100m)', location: 'Area 2', evidence: '45m to water channel', reason: 'Statutory non-buildable setback under RW CEKAL.' },
        { title: 'On-Site Stormwater Detention', location: 'Entire Site', evidence: '4,120 m³ required', reason: 'MSMA 2nd Edition stormwater compliance.' },
      ],
      opportunities: [
        { title: 'Phase 1 Residential Landed Cluster', location: 'Area 1', evidence: 'Suitability 82.5/100', reason: 'Elevated topography with minimal flood exposure.' },
        { title: 'Blue-Green Stormwater Park', location: 'Area 2', evidence: 'Water & vegetation cover 82%', reason: 'Multi-functional retention amenity and ecological corridor.' },
      ],
      recommended_actions: [
        { priority: 'Immediate', title: 'Enforce 100m River Setback in Area 2', description: 'Prevent structural development within the active riparian zone.' },
        { priority: 'Short-term', title: 'Require MSMA OSD Drainage Submissions', description: 'Integrate 4,120 m³ detention capacity into civil engineering blueprints.' },
      ],
    },
  };
}
